version: '3'
services:
  node:
    build: .
    links:
      - db
    volumes:
      - ./src/:/src
    network_mode: bridge
    ports:
      - 80:4000
    env_file: env
  db:
    image: mysql
    network_mode: bridge
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: jacee_ufes