version: '3'
services:
  node:
    build: .
    links:
      - db
    volumes:
      - ./src/:/src
    network_mode: bridge
    ports:
      - 4000:4000
    env_file: env
  db:
    image: mongo
    network_mode: bridge